apiVersion: v1
stringData:
  git_secret_token: ENC(nCFDWfkTFT9iLAfxXTS2+pRuIFXENBjuf2/VFD5FvY93x+lcOO/CanmKQWkxckXTWeMlLsCfYVQ=)
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  git_pr_token: ''
kind: Secret
metadata:
  name: git-token
type: Opaque
