apiVersion: v1
stringData:
  git_secret_token: ENC(VQRJXfpguSrWV+ElhIoh2lJ6/umMoSlxzplYKPMj0pqW2pet2FPtX0/c6eSwh4DSElrP4WOfz0k=)
  AWS_ACCESS_KEY_ID: ''
  AWS_SECRET_ACCESS_KEY: ''
  git_pr_token: ''
kind: Secret
metadata:
  name: git-token
type: Opaque
