apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(Il8idWbLCxPI4XPXTKq4qDXQcCI5i5qi)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: local-spin-cli-config
