apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(6Vu+wrIoA0aVtOfuzN/S8H/dUaHLUso9)
        username: srinivas@opsmx.io
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
