apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(jb/AorIhEhvVeu5Wqxcr9qADBSb3WCJe)
        username: srinivas@opsmx.io
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
