apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(2OSss5blrxfHfUTOUAD7Vk/CB8hzWHA4)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
