apiVersion: v1
stringData:
  config: |
    auth:
      basic:
        password: ENC(nPD+AWCX+uaVS4bIlHkx2tBGncxEjd+6)
        username: admin
      enabled: true
    gate:
      endpoint: http://sapor-gate:8084
kind: Secret
metadata:
  name: spin-cli-config
